/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,html}"
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "on-primary-fixed": "#1a1c1d",
        "surface-container-lowest": "#0e0e10",
        "secondary": "#c6c5cf",
        "on-tertiary": "#303037",
        "surface-container-low": "#1b1b1d",
        "on-secondary-container": "#bcbbc5",
        "on-background": "#e5e1e4",
        "inverse-primary": "#5d5e60",
        "tertiary-fixed": "#e3e1ea",
        "surface-container": "#201f21",
        "secondary-fixed": "#e3e1ec",
        "secondary-fixed-dim": "#c6c5cf",
        "surface-tint": "#c6c6c7",
        "on-primary-fixed-variant": "#454748",
        "error": "#ffb4ab",
        "inverse-surface": "#e5e1e4",
        "on-error-container": "#ffdad6",
        "surface-dim": "#131315",
        "background": "#131315",
        "surface-variant": "#353437",
        "on-surface": "#e5e1e4",
        "on-primary": "#2f3132",
        "on-surface-variant": "#c4c7c9",
        "on-primary-container": "#636466",
        "outline-variant": "#444749",
        "tertiary-container": "#e3e1ea",
        "primary-fixed": "#e2e2e3",
        "secondary-container": "#4a4b53",
        "primary-container": "#e2e2e3",
        "inverse-on-surface": "#303032",
        "tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#46464e",
        "on-tertiary-fixed": "#1b1b21",
        "surface-container-highest": "#353437",
        "on-error": "#690005",
        "on-tertiary-container": "#64646b",
        "surface-container-high": "#2a2a2c",
        "on-tertiary-fixed-variant": "#46464d",
        "surface-bright": "#39393b",
        "on-secondary-fixed": "#1a1b22",
        "primary": "#ffffff",
        "primary-fixed-dim": "#c6c6c7",
        "outline": "#8e9193",
        "tertiary-fixed-dim": "#c7c5ce",
        "on-secondary": "#2f3038",
        "surface": "#131315"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "1rem",
        "space-sm": "0.5rem",
        "gutter-tablet": "1.25rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "gutter-desktop": "1.5rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "label-md": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Hanken Grotesk", "sans-serif"]
      }
    }
  },
  plugins: [],
}
